---
title: "NYC restaurant inspection dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE, echo = FALSE}
library(tidyverse)
library(p8105.datasets)
library(httr)
library(jsonlite)
library(plotly)
library(lubridate)
```

```{r, include = FALSE, echo = FALSE}
get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/43nn-pn8j.json"

nyc_inspections = 
  get_all_inspections(url) %>%
  bind_rows() 
```

```{r, include = FALSE, echo = FALSE}
nyc_inspections_cleaned =
  nyc_inspections %>%
  janitor::clean_names() %>%
  mutate(date = as.Date(inspection_date),
         score = as.integer(score)) %>%
  select(
    date, boro, score, grade) %>%
  filter(
    grade == c("A","B","C"), boro == c("Bronx","Brooklyn","Manhattan","Queens","Staten Island")
  ) %>%
  drop_na(score)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Line plot

```{r}
nyc_inspections_cleaned %>%
  mutate(date = format(date, "%Y-%m")) %>%
  group_by(date, boro) %>%
  summarize(count = n()) %>%
  ungroup() %>%
  plot_ly(x = ~date, y = ~count, color = ~boro, type = "scatter", 
          mode = "lines", alpha = .5) %>%
  layout(title =  "Number of B or C grade received restaurant cases over time in NYC boroughs",
         xaxis = list(title = "Date (Year-Month)"),
         yaxis = list(title = "Cases Count"),
         font = list(size = 9)
         )
```

Column {data-width=500}
-----------------------------------------------------------------------

### Boxplot

```{r}
nyc_inspections_cleaned %>%
  mutate(year = year(date)) %>%
  plot_ly(x = ~boro, y = ~score, type = "box",
    color = ~boro, alpha = .5) %>%
  layout(title = "The distribution of restaurant scores in NYC boroughs per year",
         xaxis = list(title = "Borough"),
         yaxis = list(title = "Score"),
         font = list(size = 9))
```

### Barplot

```{r}
nyc_inspections_cleaned %>% 
  mutate(year = year(date),
         text_label = str_c("Grade: ", grade)) %>%
  group_by(year, boro, grade) %>%
  summarize(count = n()) %>%
  ungroup() %>%
  plot_ly(x = ~boro, y = ~count, color = ~grade, 
          type = "bar", alpha = 0.7) %>% 
  layout(title = 
           "Number of restaurant cases by grade level over time in NYC Boroughs",
         xaxis = list(title = "Borough"),
         yaxis = list(title = "Cases Count"),
         font = list(size = 9))
```
