---
title: ""
output:
  html_document: 
    toc: false
editor_options: 
  chunk_output_type: console
---

&nbsp;

### 1. Broadening gene discovery for AD by incorporating additional cardiovascular and cerebrovascular risk factors and examining the multi-omics profiles of genes to unravel their mechanisms and causal pathways


##### 1.1 [Multi-ancestry Genome-wide Gene-Vascular Risk Factors Interaction Analyses in Alzheimer’s Disease](https://alz.confex.com/alz/2024/meetingapp.cgi/Paper/93041)

####### Background

Cardio and cerebrovascular risk factors (CVRFs) increase the risk of cerebrovascular disease and clinical Alzheimer’s Disease (AD), and over 70% of the patients with AD coincident cerebrovascular pathology. We previously found that FMNL2 interacts with a burden score of hypertension, diabetes, heart disease, and body mass index (BMI) by altering the normal astroglial-vascular mechanisms that underly amyloid clearance. Stroke, defined by history of a clinical stroke or brain imaging, is a moderately robust risk factor for AD and dementia. The goal here was to identify genes that interact with CVRFs, incorporating stroke as an additional factor, on AD in multi-ethnic cohorts.

####### Method

We conducted a genome-wide gene-CVRF score interaction analysis for AD, in 7,939 AD patients and 9,631 controls from eight multi-ethnic cohorts of non-Hispanic Whites, African Americans, and Hispanics including ADNI, NACC, NOMAS, WHICAP, EFIGA, and ROSMAP. A CVRF score was created from the first principal component of history of clinical stroke, hypertension, diabetes, and heart disease, and measured BMI. Gene-based interaction test was performed with the adaptive gene-environment interaction test. Results were summarized using a meta-analysis. We investigated the association of pathological AD, amyloid-β, or brain infarcts with gene expression and protein expression from the frontal cortex in ROSMAP using a generalized linear model. Age, sex, and the first three principal components were adjusted in the models.

####### Result

The interaction of CVRF score with FMNL2 on AD (p=1.02E-05) was identified and additional genes were identified to interact with CVRF score, including SLC22A14 (p=1.44E-06), AMMECR1L (p=2.74E-06), PRG3 (p=2.76E-06), CFAP99 (p=5.22E-06), ADPGK-AS1 (p=8.58E-06) and BRINP1 (p=6.29E-06). ADPGK-AS1 and FMNL2 gene expressions were associated with pathological AD (p=0.004 and p = 0.0002). FMNL2 and BRINP1 gene expressions were higher in the brains of patients with brain infarcts (p = 0.025 and p = 0.006). BRINP1 protein expression was associated with pathological AD (p=0.0002) and was higher in the brains of patients with brain infarcts (p = 0.022).

####### Conclusion 

We identified novel candidate genes that interact with CVRFs on AD in multi-ethnic cohorts. Understanding the interplay between genes, CVRFs, and AD has the potential to reveal novel molecular targets for prevention and treatment for AD.

##### 1.2 Multi-omics integration via Similarity Network Fusion (SNF) for identifying molecular subtypes of aging, for effective treatments with cerebrovascular factors

&bull; Multi-omic integration via similarity network fusion to detect molecular subtypes of aging ([Silde](projects/Multi-omic integration via similarity network fusion to detect molecular subtypes of ageing.pdf))

&bull; Molecular subtyping of Alzheimer’s disease using RNA sequencing data reveals novel mechanisms and targets ([Slide](projects/molecular subtyping.pdf))

##### 1.3 Multi-ancestry mQTL analysis of human brain identifies candidate causal variants for brain-related traits

### 2. Enhancing Breast Cancer Risk Prediction in Hispanic Women Through Transfer Learning

[Interim Report](research/transfer_learning_intrm.pdf)

### 3. Data-driven dynamic modeling for AD progression

### 4. Adaptive Treatment Design and Multi-Armed Bandit Optimization